apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
spec:
  replicas: 1  # Number of instances
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration
        image: registration:latest  # Replace with your Docker image name
        imagePullPolicy: Never
        ports:
        - containerPort: 5000  # Port inside the container

---
apiVersion: v1
kind: Service
metadata:
  name: registration
spec:
  type: NodePort
  selector:
    app: registration
  ports:
    - protocol: TCP
      port: 5000       # Port exposed by the service
      targetPort: 5000  # Port of the container
